apiVersion: noops.local/v1alpha1
kind: Version
metadata:
  name: demo
spec:
  # one: # Only one version at a time
  #   app_version: sha-7c5a0d8

  multi: # Multiple versions + Canary or Blue/Green support + Dedicated endpoints support
  - app_version: sha-7c5a0d8
    weight: 10
    dedicated-endpoints: true # default to false when canary is used
  - app_version: sha-8c5a0d9
    weight: 90
    args:
    - --set
    - env.service_version=vCUSTOM
  # - app_version: sha-8c5a0d9
  #   # version: 10.0.0 # optional
  #   # build: 30        # optional
